### PR TITLE
Make save() function consistant 

### LINKED ISSUE #742: save() function inconsistency
If you create a new image, you can save it using img.save(filename); but if you open an existing image, doing img.save(filename) doesn't work.
See https://users.rust-lang.org/t/can-create-save-an-image-but-cant-load-modify-save-one/16574

### PR DESCRIPTION
**Pull request by calum**
This PR makes the two `save` functions for `DynamicImage` and `ImageBuffer` the same and renames the old `DynamicImage` `save` to be ~`write`~ `write_to` instead.

This fixes #742.

### CODE REVIEW

**Comment by HeroicKatora** [comment]
I am reluctant to choose the name `write` however consolidating on `save` for file operations is good for consistency and ergonomics. But in my head, `write` is too closely linked to `std::io::Write`, maybe `write_to` instead?

**Comment by calum** [comment]
Thank you for the feedback. 

I see what you mean. I prefer `write_to`.

**Comment by bvssvni** [comment]
Merging.

**Comment by bvssvni** [comment]
Thanks!

**Pull request merged**
