### PR TITLE
Add sepia to colorops

### PR DESCRIPTION
**Pull request by RedRoosterMobile**
sepia filter from webkit

css equivalent:
`filter: sepia(100%)`

normal:
test

sepia(1.0): // 0.0 min to 1.0 max
test2

### CODE REVIEW

**Comment by RedRoosterMobile** [comment]
last test timed out. I can't restart it, since I don't have the rights

**Comment by bvssvni** [comment]
@RedRoosterMobile I've restarted the build.

**Comment by RedRoosterMobile** [comment]
thanks for restarting, all green now :-)

**Comment by bvssvni** [comment]
@RedRoosterMobile Have you seen https://github.com/PistonDevelopers/image/issues/608?

**Comment by bvssvni** [comment]
I think this should be in imageproc. Closing.

**Pull request closed without merging**
