### PR TITLE
Add convenient save method on ImageBuffer

### PR DESCRIPTION
**Pull request by Ryman**
Also standardise on the spelling of Gray across the repo. I chose Gray as the TIFF spec has tags with the American spelling.

### CODE REVIEW

**Comment by nwin** [comment]
I think Gray is a good choice, we are using AE anyway (--> color).

Could you please remove the unsafe block from the saving method that is not necessary. If you have borrowing problem you have to save the width and height to a variable first.

**Comment by Ryman** [comment]
It's not a borrowing problem, it was a coherence thing, but I finally figured out the required syntax, so it's unnecessary now :) Pushed updated commits, pending on travis.

**Comment by nwin** [comment]
Can you please rebase to the latest rustc change?

**Comment by Ryman** [comment]
@nwin Rebased and removed some warnings (last commit). I didn't add feature flags for rustc_private as it' probably something that might actually be worth investigating.

**Comment by nwin** [comment]
Omg…what happened to rust?

Thank you for your contribution!

**Pull request merged**
