### PR TITLE
fix black top-left border after resize (issue #197)

### PR DESCRIPTION
**Pull request by pavlov-dmitry**
fix black top-left border after resize (issue [#197](https://github.com/PistonDevelopers/image/issues/197))

### CODE REVIEW

**Comment by iirelu** [comment]
Haha, I was just about to report this annoying bug. I'd love to see this PR merged soon.

**Comment by nwin** [comment]
Nice catch! But I suppose we should use i64 instead to avoid overflow. Could you please change that?

**Comment by iirelu** [comment]
@nwin Why would you be using u32s in the first place if you were worried about images with dimensions larger than a few billion?

**Comment by pavlov-dmitry** [comment]
I think it is almost impossible to overflow in real world, but
this bug is so annoying that I didn't want to argue about overflows. I will change it.

**Comment by nwin** [comment]
@iirelu because u32 is the maximum size supported by all image formats we support.

Thanks, pavlov!

**Pull request merged**
