### PR TITLE
Do not expose `byteorder::Error`

### PR DESCRIPTION
**Pull request by bvssvni**
Closes https://github.com/PistonDevelopers/image/issues/487

- Hide all methods on `TIFFDecoder` except `new`
- Hide `tiff::ByteOrder` as it is not needed in public API
- Moved `ifd` and `stream` to submodules of `decoder` to solve internal
visibility issues

### CODE REVIEW

**Comment by bvssvni** [comment]
@nwin Do these changes look OK?

**Comment by nwin** [comment]
Yes, thanks.

**Comment by bvssvni** [comment]
I think we could bump the patch version since there are likely no libraries using these methods.

**Comment by nwin** [comment]
Yes.

**Pull request merged**
