### PR TITLE
Upgrade byteorder to 0.5.1

### PR DESCRIPTION
**Pull request by jaysonsantos**
If possible, would you release a new version?

### CODE REVIEW

**Comment by bvssvni** [comment]
Nice!

Will release a 0.9.0 version.

**Comment by jaysonsantos** [comment]
I just rebased to change the aliases IoError and IoErrorKind to use the namespace io instead.

**Comment by bvssvni** [comment]
Looks good! Merging.

**Comment by jaysonsantos** [comment]
Thanks @bvssvni, do you have an ETA on the new version?

**Comment by bvssvni** [comment]
@jaysonsantos Published 0.9.0

**Comment by jaysonsantos** [comment]
Thanks @bvssvni

**Pull request merged**
