### PR TITLE
Replace in-tree JPEG decoder with the jpeg-decoder crate

### LINKED ISSUE #474: Panic when reading jpeg
```rust
extern crate image;

use std::io::Cursor;
use image::ImageDecoder;

fn main() {
    let input = b"\xff\xda\x30\x30\x30\x30\x30".to_vec();
    let c = Cursor::new(input);
    let _ = image::jpeg::JPEGDecoder::new(c).read_image();
}
```

```
coreyf@frewbook-pro /t/tmp (master)> cargo run
   Compiling tmp v0.1.0 (file:///private/tmp/tmp)
     Running `target/debug/tmp`
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:365
Process didn't exit successfully: `target/debug/tmp` (exit code: 101)
```

found using [afl.rs](https://github.com/frewsxcv/afl.rs)

### PR DESCRIPTION
**Pull request by kaksmet**
This adds support for progressive JPEGs.

[jpeg-decoder](https://crates.io/crates/jpeg-decoder) is also 1.52x faster to decode a 3000x2000 4:2:0 baseline JPEG compared to the in-tree JPEG decoder it replaces on my computer.

Closes #474 #114

### CODE REVIEW

**Comment by bvssvni** [comment]
@kaksmet You are awesome! :smile:

**Comment by bvssvni** [comment]
@nwin Are you ok with merging this?

**Comment by nwin** [comment]
Looks fine to me. We should definitively add some progressive test images to this. @kaksmet could you please do that? Ideally some of the servo repository, please see #413 for some examples.

**Comment by kaksmet** [comment]
I added the three progressive JPEGs found in #413. Is that enough or do you want me to add more?

**Comment by bvssvni** [comment]
Looks good. Merging.

**Pull request merged**
