### PR TITLE
Add fuzzing scripts

### PR DESCRIPTION
**Pull request by neosilky**
I've added fuzzing scripts to decode each format explicitly and one that runs the generic `load_from_memory` function.

I've got some crashes in incoming issues and PRs.

### CODE REVIEW

**Comment by nwin** [comment]
Thank you, I’m not aware of this fuzzing framework. Is it something which could be automatically run?

**Comment by neosilky** [comment]
Hey @nwin! The framework is [cargo-fuzz](https://github.com/rust-fuzz/cargo-fuzz) and can easily be run by using `RUST_BACKTRACE=1 cargo fuzz run fuzzer_script_1 -- -max_len=10240`.

I've got a few crashes which I am just triaging... :)

**Comment by neosilky** [comment]
ping @nwin

**Comment by nwin** [comment]
ok, looks good, sorry for the delay :)

**Pull request merged**
