### PR TITLE
Use external PNG crate.

### LINKED ISSUE #390: Add compression to PNG
The ability to compress PNG images was reduced in order to make it work with Rust 1.0 beta that should be added back at some point…

### PR DESCRIPTION
**Pull request by nwin**
Image::png is now just a little layer over an external codec crate.

Closes #390 #300 #400 #414

### CODE REVIEW

**Comment by nwin** [comment]
Note this is WIP. I will move the png crate to PistonDevelopers before merging.

**Comment by tomaka** [comment]
According to one of the Servo devs (don't remember who), using C code defeats the purpose of using image in the first place.

**Comment by nwin** [comment]
Servo already depends on flate2. At least @kmcallister seemed to be fine with it.

**Comment by bvssvni** [comment]
@nwin You are awesome!

**Comment by bvssvni** [comment]
@tomaka I opened https://github.com/PistonDevelopers/image/issues/419

**Comment by LaylConway** [comment]
Having a pure rust implementation for most things would be preferable in my opinion.

**Comment by bvssvni** [comment]
@LaylConway See https://github.com/PistonDevelopers/image/issues/419

**Comment by nwin** [comment]
So the updated PNG crate now uses flate2 only for encoding.

**Pull request merged**
