### PR TITLE
Add Format from Memory

### PR DESCRIPTION
**Pull request by TheNeikos**
I was missing this functionality as I would like to keep the original format from a file on files uploaded by users.

### CODE REVIEW

**Comment by nwin** [comment]
Thank you for contributing. Can you please give the function a more compelling name for example 'guess_format' and also use it in 'load_from_memory' as the patch is now we have  code duplication.

**Comment by TheNeikos** [comment]
Alright, how does that look like?

**Comment by TheNeikos** [comment]
Okay, so this job errored: https://travis-ci.org/PistonDevelopers/image/jobs/153595100

With no error :v so I'm a bit confused. 

Could someone restart that build?

**Comment by nwin** [comment]
That looks good, thank you!

**Comment by TheNeikos** [comment]
When do you think is there going to be a new release? Do you have some sort of cycle?

**Pull request merged**
