### PR TITLE
Switch to using lzw crate instead of using a built in version

### PR DESCRIPTION
**Pull request by fintelia**
This change also fixes issue #706.

### CODE REVIEW

**Comment by nwin** [comment]
Thank you very much. Looks good to me, but can you please remove the utils mod altogether? It is not needed anymore.

**Comment by nwin** [comment]
Do you, by any chance, have a smaller example image to hand, which exhibits the same issue as #706?

**Comment by fintelia** [comment]
The utils module still contains `expand_packed` which is needed by buffer.rs. Although that function could probably be moved elsewhere if you prefer.

[test-images.zip](https://github.com/PistonDevelopers/image/files/1587775/test-images.zip) contains a couple smaller images that have the same issue as in #706. Inside the zip archive, good-lzw.tiff is the original (valid) TIFF file, while bad-lzw.tiff and bad-lzw2.tiff have been manually altered to have two different variants of the encoding bug.

**Comment by fintelia** [comment]
Oops, that zip archive wasn't quite right. Use this one instead: [test-images-v2.zip](https://github.com/PistonDevelopers/image/files/1587784/test-images-v2.zip)

**Comment by nwin** [comment]
Great thanks!

**Pull request merged**
