### PR TITLE
Add PackBits decoding to TIFF

### PR DESCRIPTION
**Pull request by aschampion**
This is my first Rust PR and I only have a few thousand lines experience with Rust, so let me know if there are obvious style/idiom/perf deficiencies.

The other stream decoders weren't documented so I didn't bother. A test is included. I've also manually tested end-to-end with both 8- and 16-bit TIFFs encoded with PackBits by a few different programs.

### CODE REVIEW

**Comment by aschampion** [comment]
Anything I can do to help move this towards a merge?

**Comment by bvssvni** [comment]
Looks good to me!

@nwin Thoughts?

**Comment by nwin** [comment]
Thank your for the PR. Looks fine to me. Could you please change wrap to new? This is the convention in Rust. 

Furthermore please add a test file which is using packbits to prevent regressions.

**Comment by aschampion** [comment]
Thanks, changes made/pushed and the image test also caught a bug which is fixed.

**Comment by bvssvni** [comment]
Nice! Merging.

**Pull request merged**
