### PR TITLE
Use a reference to a Writer in DynamicImage::save

### LINKED ISSUE #276: DynamicImage::save should take the writer by mutable reference.
```fn save<W: Writer>(&self, w: W, format: ImageFormat) -> IoResult<ImageResult<()>>```
should be

```fn save<W: Writer>(&self, w: &mut W, format: ImageFormat) -> IoResult<ImageResult<()>>```

### PR DESCRIPTION
**Pull request by nwin**
Closes #276.

### CODE REVIEW

**Comment by nwin** [comment]
Also testing this edit-to-branch feature of github.

**Comment by bvssvni** [comment]
This leads to a bunch of errors. I'm closing this since it probably needs to compile locally first.

**Comment by TyOverby** [comment]
No reason to close pull requests that aren't yet ready.

**Comment by bvssvni** [comment]
@TyOverby nwin used the quick-push feature, where a branch is created on the fly when committing through the browser.

**Comment by TyOverby** [comment]
Oh, that makes sense.  Looks like PngEncoder needs to be changed to allow this.

**Comment by bvssvni** [comment]
@TyOverby Feel free to make go at it.

**Comment by nwin** [comment]
You can close it and make it on another branch, I thought it was a quick fix.

**Pull request closed without merging**
