### PR TITLE
Update for latest Rust

### PR DESCRIPTION
**Pull request by bombless**
Update for https://github.com/rust-lang/rust/pull/23399

### CODE REVIEW

**Comment by tomaka** [comment]
Would be nice to publish this on crates.io as well.

**Comment by tomaka** [comment]
@bvssvni @nwin ping!
The version on crates.io right now doesn't compile.

**Comment by bombless** [comment]
@tomaka I think it's because the semver didn't update.

**Comment by nwin** [comment]
No, we that’s because we don’t automatically push to crates.io. Done

**Comment by bombless** [comment]
@nwin Thanks for the info :smile:

**Comment by tomaka** [comment]
Thanks!

**Pull request merged**
