### PR TITLE
Use stable Rust instead of 1.0.0

### PR DESCRIPTION
**Pull request by tomaka**

### CODE REVIEW

**Comment by ruud-v-a** [comment]
Instead of testing on stable _or_ 1.0, why not test both? As long as we do not use any of the new stuff, we can continue to support 1.0, right?

**Comment by nwin** [comment]
@ruud-v-a Testing against both would increase the testing time even more.

I thing we should just keep supporting 1.0 unless we really need a feature from stable.

**Comment by ruud-v-a** [comment]
Don’t the builds run in parallel? At least for this PR the logs show the same start time for every build.

**Comment by frewsxcv** [comment]
Opened a new PR that addresses the comments in here #472

**Comment by bvssvni** [comment]
Closed in favor of https://github.com/PistonDevelopers/image/pull/472

**Pull request closed without merging**
