### PR TITLE
Remove Frames, add FrameIterator that reads the frames in a lazy manner.

### PR DESCRIPTION
**Pull request by ArturKovacs**
Implements a solution for #823.

Suggestions are welcome.

### CODE REVIEW

**Comment by ArturKovacs** [comment]
It may be better to have `gif::Encoder::encode_frames` take an `Iterator<Item = animation::Frame>` or simply a `&Vec<animation::Frame>`  instead of an `Iterator<Item = ImageResult<animation::Frame>>`. Also `FrameIterator` could actually just be named `Frames` just like before.

What do you think?

**Comment by bvssvni** [comment]
I think "Frames" sounds better than "FrameIterator".

**Comment by ArturKovacs** [comment]
Yes, I actually agree. Alright I will wait for #798 to be merged and as soon that's done I will probably delete this PR and make a new one, based on those changes.

**Comment by bvssvni** [comment]
Nice! I was wondering about that. I'll check in tomorrow to see if there any objections, but I expect that https://github.com/PistonDevelopers/image/pull/819 will be go smoothly (it has been open since October and nobody has objected yet).

**Comment by ArturKovacs** [comment]
New pull request, implementing changes on the latest commit will be opened.

**Pull request closed without merging**
