### PR TITLE
Updated crates.io

### PR DESCRIPTION
**Pull request by bvssvni**
DO NOT MERGE YET!

- Bumped to 0.6.1

### CODE REVIEW

**Comment by bvssvni** [comment]
The rand crate fails on Rust nightly https://github.com/rust-lang/rust/issues/30713.

`rustc 1.7.0-nightly (d5e229057 2016-01-04)`

**Comment by tafia** [comment]
I think this is not a breaking change as these fn already had a default
impl through GenericImage.

**Comment by bvssvni** [comment]
@tafia Perhaps the new methods should be moved [here](https://github.com/PistonDevelopers/image/blob/c5e7ca986139006ef77478cfe5cf1f7496401f3e/src/buffer.rs#L448)?

**Comment by bvssvni** [comment]
@tafia I moved the methods to the `GenericImage` impl. Changed the version to 0.6.1. Had to change from `&P` to `P` when returning from `unsafe_get_pixel`.

**Comment by bvssvni** [comment]
Merging.

**Pull request merged**
