### PR TITLE
Update png and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by Eijebong** [comment]
Ping ? :)

**Comment by bvssvni** [comment]
I think we should try to merge some PRs from the queue first.

**Comment by nox** [comment]
@bvssvni This crate really needs additional maintainers then, this bump has been here for more than a week, all to bring a `png` fix that also stalled for more than a week.

**Comment by bvssvni** [comment]
@nox I agree.

**Comment by fintelia** [comment]
At this point none of the remaining PRs in the queue include breaking changes so they can be added in a point release. I'm OK with merging this, but I don't know how to go about deploying to crates.io

**Comment by bvssvni** [comment]
Perhaps wait for https://github.com/PistonDevelopers/image-png/pull/100, so we can skip to Png 0.14.0.

**Comment by Eijebong** [comment]
Yup, let's wait if png is going to be released soon-ish

**Comment by bvssvni** [comment]
png 0.14 is now released: https://crates.io/crates/png

**Comment by Eijebong** [comment]
Updated the version

**Comment by bvssvni** [comment]
Merging.

**Comment by bvssvni** [comment]
Thanks!

**Comment by nox** [comment]
Great! Will you be able to publish it today?

**Comment by bvssvni** [comment]
I need to update the version log first.

**Pull request merged**
